const express=require('express')
const fundingPersonalInformationRouter=express.Router()
const fundingPersonalInformationController=require('../controller/fundingPersonalInformationController')
fundingPersonalInformationRouter.post('/fundingPersonalInformation',fundingPersonalInformationController.postFundingPersonalInformation)
fundingPersonalInformationRouter.get('/getAllPersonInformation',fundingPersonalInformationController.getAllPersonInformation)
fundingPersonalInformationRouter.get('/:id',fundingPersonalInformationController.getPersonInformationById)

module.exports =fundingPersonalInformationRouter